### ISSUE TITLE
Susceptibility isn't always a good observable

### ISSUE THREAD

**Issue by alcherman** [evanberkowitz/supervillain#131]
We have been using the susceptibility (e.g. spin susceptibility) as a way to probe long-distance physics.  This only works if the associated operator has scaling dimension $\Delta<1$, because then $\chi = \int d^{2}x \langle O(x) O(0) \rangle$ has a long-distance divergence, and is dominated by the long-distance limit of $\langle O(x) O(0) \rangle$.

For $W\ge 3$, $e^{i\varphi}$ has $\Delta >1$, the integral defining $\chi$ converges, and no longer cares about the long-distance part of the correlator.  So this no longer works, see the plot below.

To get around this we should just look at the correlator itself, not its integral.  The maximal separation on the lattice is  N/2, so we can measure

$correlator_{N/2} * (N/2)^{2\Delta_{\rm critical}}$

as a function of N and kappa.  It should go flat at the critical value of \kappa.

[SpinSusceptibilityScaled_W=3.pdf](https://github.com/evanberkowitz/supervillain/files/14406846/SpinSusceptibilityScaled_W.3.pdf)

**Comment by evanberkowitz** [comment]
Before I implement this, let me suggest a way to improve the statistics.  What I'm worried about is that at the maximal displacement the value of the correlator will be small, so noise can hurt us.

Suppose 

$$C_\kappa(x) = \langle O(x) O(0) \rangle.$$

If $C_\kappa$ decays polynomially, $C_\kappa(x) = 1/x^{2\Delta_\kappa}$ then we can multiply by $x^{2\Delta_c}$ to get 

$$D_\kappa(x) = x^{2\Delta_c} C_\kappa(x) = 1/x^{2(\Delta_\kappa-\Delta_c)}$$

Then $D_\kappa$(maximal displacement) is independent of the size of the lattice when $\kappa$ is tuned to its critical value, hence the measurement you're suggesting above.

But in fact, at critical $\kappa$ that correlator is 1 independent of $x$!  So at the critical $\kappa$ we should be able to average $D$ over x and find 1,

$$ 1 = \frac{1}{N_x^2} \sum_{\vec{x}} D_{\kappa_c}(\vec{x}) $$

independent of Nx.

Questions: 

 - Does this make sense to compute as a way to detect the transition?
 - Does it work for any W? (It'd be nice to only explain 1 probe rather than say: look when W<=2 we use this and when W>= 3 we use that.)

**Comment by evanberkowitz** [comment]
Here is a computation of D from C on a 12x12 lattice with W=1 and kappa=0.74.  To my surprise D isn't 
 - flat
 - equal to 1?  (At x=0 I multiplied by 0, so that I understand, but what is this ~0.8 value?)

![Screenshot 2024-04-25 at 15 37 01](https://github.com/evanberkowitz/supervillain/assets/129339/55481147-4a6b-4dd7-88a4-3d92e39567e2)

**Comment by evanberkowitz** [comment]
Let's define the 'critical moment' of the spin correlator

$$ C_S = \frac{1}{N_x^2} \int_{0,0}^{N_x,N_x} d^2x\ S(x)\ x^{2 \Delta_S(\kappa_c)} $$

and analogously the critical moment of the vortex correlator

$$ C_V = \frac{1}{N_x^2} \int_{0,0}^{N_x,N_x} d^2x\ V(x)\ x^{2 \Delta_V(\kappa_c)} $$

As $\kappa > \kappa_c$ the vortex operator will become more and more irrelevant and its scaling dimension will grow $\Delta_V(\kappa) > \Delta_V(\kappa_c)$.  Just above $\kappa_c$ on the cft side $V \sim 1/x^{2\Delta_V(\kappa)}$ so the integrand will look like `1/x^{small power}`.  Given that the integral

$$\sim \int_0^\Lambda dr\ 2\pi r \times r^{-\textrm{small power}} \sim \Lambda^{2-\text{small}}$$

the normalization by $\Lambda^2$ will make $C_V$ ultimately go to 0 with large volume.  On the gapped side the integral will be finite and again the normalization will send $C_V$ to 0 with large volume.  But the critical kappa will integrate 1 over the volume, and the normalization will set $C_V$ to 1 in the limit of large volume.

In this little example we mock up a V that depends on Δ: on the CFT side it's polynomial decay and on the gapped side it's exponential.  For each W the orange triangles are when $\Delta_V=\Delta_V(\kappa_c)$.  Blue circles is the gapped side, with exponential decay, red diamonds and green squares are deeper into the CFT.  The three panels mock up W=1, 2, and 3.

![Screenshot 2024-04-26 at 11 07 57](https://github.com/evanberkowitz/supervillain/assets/129339/196b0ce9-5f9c-43cb-b571-364a72adc620)

In contrast, the spin operator behaves differently.  When $\kappa > \kappa_c$ the scaling dimension is less than the critical value, so the integrand will look like `x^{positive power}`, not decaying!
Then the integral will look like

$$\sim \int_0^\Lambda dr\ 2\pi r \times r^{+\textrm{small power}} \sim \Lambda^{2+\textrm{small power}}$$

and the normalization by $\Lambda^2$ will still allow $C_S$ to diverge with the volume.  On the gapped side the exponential decay will cause the integral to converge and the normalization will send $C_S$ to 0 in the infinite volume limit.  But at the critical kappa we will again integrate 1 over the volume and the normalization will set $C_S$ to 1 in the limit of large volume.

In this little example we mock up an S that depends on Δ: on the CFT side it's polynomial decay and on the gapped side its exponential.  But the CFT side has the opposite behavior.  In these figures (W=1,2,3) blue circles and orange triangles have $\Delta < \Delta_S(\kappa_c)$ and diverge, red diamonds have critical behavior at 1, and green squares decay to 0.

![Screenshot 2024-04-26 at 11 41 03](https://github.com/evanberkowitz/supervillain/assets/129339/6e0f0381-3878-4e36-a9ad-364522c98070)
